project:
  type: website
  # output-dir: ../docs
  
website:
  favicon: images/fav-icon2.png
  image: images/fav-icon2.png
  
  twitter-card: true
  open-graph: true
  google-analytics: "G-H9Z8DC0X8Q"
  title: "What's Seattle Reading?"
  site-url: melaniewalsh.github.io/whats-seattle-reading
  page-footer:
    background: "#455B64"
  # right: <p style="color:white">Copyright &copy; 2024</p>

  navbar:
    logo: images/fav-icon2.png
    right:
      - explore.qmd
      - people.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/melaniewalsh/whats-seattle-reading
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    # include-in-header: scripts/table-tweak.js
    theme: 
     - flatly
    #  - styles.css
    #  - custom.scss
    linkcolor: " #44afd9"
    css:
     - styles.css


resources:
  - CNAME



